arb-dir: lib/l10n # ARBファイルを格納するディレクトリを指定します。
template-arb-file: app_ja.arb # テンプレートのARBファイルを指定します。デフォルトの言語のARBファイルを設定すると良いと思います。 
output-class: L10n # 自動生成されるクラス名。設定しないとAppLocalizationsになります。
output-localization-file: app_localizations.dart # 自動生成される言語ファイル名。ローカライゼーションを使うときはこのファイルをインポートします。
synthetic-package: false #　falseの時、output-dirで指定したフォルダにLocalizationコードを生成する。trueなら.dart_tool/flutter_gen/gen_l10nに生成