name: flutter_application
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.7.1
  flutter_localizations:
    sdk: flutter
  mockito: ^5.4.4
  liquid_swipe: ^3.1.0
  slang: ^4.5.0
  slang_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  slang_build_runner: ^4.5.0

flutter:
  uses-material-design: true

  # flutter_localizationsを追加した時に追記した
  generate: true
